### PR TITLE
rollup fixes and features for release/REL-2.4.0_emc 

### PR DESCRIPTION
**Pull request by BenjaminTJohnson**
This rolls up several items into the REL-2.4.0_emc release branch, most of which are pulled from crtm_jedi_v2.4.0.
Specifically:

(1)  Adds netCDF IO support for ACCoeff, NLTECoeff, SpcCoeff, and TauCoeff files.

(2)  adds check for SpcCoeff%PolAngle when reading in SpcCoeff files, to support recently created N21 files that contain the PolAngle field.  This required updates or newly added files,  `/libsrc/CMakeLists.txt`, `libsrc/CRTM_MW_Water_SfcOptics.f90`, `libsrc/CRTM_SfcOptics.f90`,  `libsrc/CRTM_SpcCoeff.f90`, `libsrc/SensorInfo_Define.f90`, `libsrc/SensorInfo_IO.f90`, `libsrc/SensorInfo_Parameters.f90`, `libsrc/SpcCoeff_Define.f90`, `libsrc/SpcCoeff_Binary_IO.f90`, `libsrc/SpcCoeff_IO.f90`, `libsrc/SpcCoeff_Parameters.f90`

(3) Updated `CRTM_Version.inc` to be "v2.4.0"

(4) Added RSS_Emissivity module to support L-band MW ocean surface emissivity.

(5) test harness changes (`test/CMakeLists.txt`)
(a)  now all `cmake` based, no longer requires `ecbuild` to run
(b)  updated for newer coefficients
(c)  works if `fix/` directory is present (default for this branch), if not, downloads tarball.
(d) adds the `SpcCoeff_Inspect` utility as a test.  See `test/CMakeLists.txt` file to modify the input sensor or run it from command line.

### CODE REVIEW

**Comment by BenjaminTJohnson** [comment]
@CoryMartin-NOAA @emilyhcliu in this PR, I intend to update the current tagged release that EMC uses for CRTM v2.4.0.  It fixes an issue that Andrew C. reported to me with respect to the atms_n21 coefficient, and merges in some features that are present in the jedi v2.4.0 release.    Additionally, as described, no more ecbuild requirements in the ctests.

My tests show numerically identical output from this PR and the current branch, so no results should change (other than bug fixes).  These changes will also make it easier for me to maintain consistency between the jedi-specific v2.4.0 release and the emc release.  

I don't have Andrew's github username to assign him as a review, please feel free to do so.  Happy to answer any questions.

**Comment by CoryMartin-NOAA** [comment]
@adcollard

**Comment by ADCollard** [comment]
Thanks, @BenjaminTJohnson .

I'm updating this issue with the e-mails I sent last week and then with the new information I have found since.

**Comment by ADCollard** [comment]
The first run does not appear to be playing nice with the older files:

SpcCoeff_ReadFile(Binary)(FAILURE) : Error reading channel data. input statement requires too much data, unit 10, file /scratch1/NCEPDEV/stmp2/Andrew.Collard/RUNDIRS/v16.3.6_n21_atms_test/2023071500/gdas/anal.296806/./crtm_coeffs/amsua_metop-b.SpcCoeff.bin

 CRTM_SpcCoeff_Load(FAILURE) : Error reading SpcCoeff file #1, ./crtm_coeffs/amsua_metop-b.SpcCoeff.bin

 READ_BUFRTOVS:  ***ERROR*** crtm_spccoeff_load error_status=           3

**Comment by ADCollard** [comment]
There is a bug in [SpcCoeff_Binary_IO.f90](https://github.com/JCSDA/crtm/blob/hotfix/btj_REL-2.4.0_emc_polangle/libsrc/SpcCoeff_Binary_IO.f90).  Specifically these lines:

IF( dummy%Version > 2 ) THEN
      ! Binary coefficient version 3 introduced for TROPICS instrument.
      ! The SpcCoeff coefficients contain 'PolAngle' as an additional
      ! array.
      READ ( fid, IOSTAT=io_stat, IOMSG=io_msg ) &
        SpcCoeff%Sensor_Channel            , &
        SpcCoeff%Polarization              , &
        SpcCoeff%PolAngle                  , &
        SpcCoeff%Channel_Flag              , &
        SpcCoeff%Frequency                 , &
        SpcCoeff%Wavenumber                , &
        SpcCoeff%Planck_C1                 , &
        SpcCoeff%Planck_C2                 , &
        SpcCoeff%Band_C1                   , &
        SpcCoeff%Band_C2                   , &
        SpcCoeff%Cosmic_Background_Radiance, &
        SpcCoeff%Solar_Irradiance
    ELSE IF( dummy%Version < 3 ) THEN
      ! Version 2 is the default binary SpcCoeff version for
      ! REL-2.4.0 and older.
      READ ( fid, IOSTAT=io_stat, IOMSG=io_msg ) &
        SpcCoeff%Sensor_Channel            , &
        SpcCoeff%Polarization              , &
        SpcCoeff%Channel_Flag              , &
        SpcCoeff%Frequency                 , &
        SpcCoeff%Wavenumber                , &
        SpcCoeff%Planck_C1                 , &
        SpcCoeff%Planck_C2                 , &
        SpcCoeff%Band_C1                   , &
        SpcCoeff%Band_C2                   , &
        SpcCoeff%Cosmic_Background_Radiance, &
        SpcCoeff%Solar_Irradiance

Most of the versions in fix/SpcCoeff/Big_Endian are 8.02 or (for ATMS_N21) 8.04, but amsua_metop-b is version 8.03, so dummy%Version=3.  This file does not contain PolAngle, which is why the code crashes.

The comment says that version 3 should include this field, so I do not know which is right. But changing dummy%Version > 2 to dummy%Version > 3 allows the file to be read in.

Also not that the IF( dummy%Version < 3 ) does not actually do anything!

This bug is also present in develop, so I will open an issue once I get some clarity on what v3 should contain.

**Comment by ADCollard** [comment]
There is a second issue that most of the hirs instruments have a version number of 4 or more.  So my modified version of the code will not read those properly as they are missing the polAngle.  I can work around this by turning off HIRS in the GSI (we are actually still monitoring NOAA-19 HIRS!).

**Comment by ADCollard** [comment]
I cannot push commits to this release branch, so here are the changes that are required:

```
Hera(hfe04):/scratch1/NCEPDEV/da/Andrew.Collard/git/crtm_REL-2.4.0_emc_polangle$ git diff
diff --git a/libsrc/SpcCoeff_Binary_IO.f90 b/libsrc/SpcCoeff_Binary_IO.f90
index 1a1a5d84..9761548f 100644
--- a/libsrc/SpcCoeff_Binary_IO.f90
+++ b/libsrc/SpcCoeff_Binary_IO.f90
@@ -397,7 +397,7 @@ CONTAINS
       CALL Read_Cleanup(); RETURN
     END IF
     ! ...Read the channel data
-    IF( dummy%Version > 2 ) THEN
+    IF( dummy%Version > 3 ) THEN
       ! Binary coefficient version 3 introduced for TROPICS instrument.
       ! The SpcCoeff coefficients contain 'PolAngle' as an additional
       ! array.
@@ -414,7 +414,7 @@ CONTAINS
         SpcCoeff%Band_C2                   , &
         SpcCoeff%Cosmic_Background_Radiance, &
         SpcCoeff%Solar_Irradiance
-    ELSE IF( dummy%Version < 3 ) THEN
+    ELSE IF( dummy%Version < 4 ) THEN
       ! Version 2 is the default binary SpcCoeff version for 
       ! REL-2.4.0 and older.
       READ ( fid, IOSTAT=io_stat, IOMSG=io_msg ) &
@@ -435,6 +435,7 @@ CONTAINS
     END IF
     IF ( io_stat /= 0 ) THEN
       msg = 'Error reading channel data. '//TRIM(io_msg)
+      write(*,*) 'version, sensor, satellite=',dummy%Version,SpcCoeff%Sensor_Id, SpcCoeff%WMO_Satellite_Id   
       CALL Read_Cleanup(); RETURN
     END IF
 ```

**Comment by BenjaminTJohnson** [comment]
@ADCollard I've added you to the CRTM team, so you should have push access now.

**Pull request merged**
